"""forth link fields

Revision ID: 1dabec678bd3
Revises: 2fdf0bb51422
Create Date: 2026-07-25 14:44:20.636491

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1dabec678bd3'
down_revision: str | None = '2fdf0bb51422'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohorts', sa.Column('forth_workspace_url', sa.String(length=500), nullable=True))
    op.add_column('decisions', sa.Column('forth_url', sa.String(length=500), nullable=True))
    op.add_column('help_requests', sa.Column('forth_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('forth_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'forth_url')
    op.drop_column('help_requests', 'forth_url')
    op.drop_column('decisions', 'forth_url')
    op.drop_column('cohorts', 'forth_workspace_url')
    # ### end Alembic commands ###
