"""presence, kudos and check-ins

Revision ID: 2fdf0bb51422
Revises: 6573f3d8d8d5
Create Date: 2026-07-24 17:19:56.256657

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2fdf0bb51422'
down_revision: str | None = '6573f3d8d8d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_check_ins_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_check_ins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_ins'))
    )
    op.create_index('ix_check_ins_cohort_id_created_at', 'check_ins', ['cohort_id', 'created_at'], unique=False)
    op.create_index('ix_check_ins_cohort_user', 'check_ins', ['cohort_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_check_ins_created_at'), 'check_ins', ['created_at'], unique=False)
    op.create_table('kudos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('from_user_id', sa.Uuid(), nullable=False),
    sa.Column('to_user_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=280), nullable=False),
    sa.Column('help_request_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_kudos_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('fk_kudos_from_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name=op.f('fk_kudos_help_request_id_help_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_kudos_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('fk_kudos_to_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kudos'))
    )
    op.create_index('ix_kudos_cohort_id_created_at', 'kudos', ['cohort_id', 'created_at'], unique=False)
    op.create_index('ix_kudos_cohort_recipient', 'kudos', ['cohort_id', 'to_user_id'], unique=False)
    op.create_index(op.f('ix_kudos_created_at'), 'kudos', ['created_at'], unique=False)
    op.alter_column('cohorts', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.alter_column('cohorts', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_kudos_created_at'), table_name='kudos')
    op.drop_index('ix_kudos_cohort_recipient', table_name='kudos')
    op.drop_index('ix_kudos_cohort_id_created_at', table_name='kudos')
    op.drop_table('kudos')
    op.drop_index(op.f('ix_check_ins_created_at'), table_name='check_ins')
    op.drop_index('ix_check_ins_cohort_user', table_name='check_ins')
    op.drop_index('ix_check_ins_cohort_id_created_at', table_name='check_ins')
    op.drop_table('check_ins')
    # ### end Alembic commands ###
