"""initial multi-tenant schema

Revision ID: 6573f3d8d8d5
Revises: 
Create Date: 2026-07-24 15:03:31.409379

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '6573f3d8d8d5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(sa.schema.CreateSequence(sa.Sequence('message_seq')))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index('ix_login_attempts_identifier_created_at', 'login_attempts', ['identifier', 'created_at'], unique=False)
    op.create_index('ix_login_attempts_ip_created_at', 'login_attempts', ['ip_address', 'created_at'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('redirect_to', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state', name='uq_oauth_states_state')
    )
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('slug', name='uq_skills_slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_cohorts_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorts')),
    sa.UniqueConstraint('invite_code', name='uq_cohorts_invite_code'),
    sa.UniqueConstraint('slug', name='uq_cohorts_slug')
    )
    op.create_index(op.f('ix_cohorts_created_at'), 'cohorts', ['created_at'], unique=False)
    op.create_table('email_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('verify_email', 'reset_password', name='email_token_purpose', native_enum=False, length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tokens')),
    sa.UniqueConstraint('token_hash', name='uq_email_tokens_token_hash')
    )
    op.create_index('ix_email_tokens_expires_at', 'email_tokens', ['expires_at'], unique=False)
    op.create_index('ix_email_tokens_user_id_purpose', 'email_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_account_id', sa.String(length=120), nullable=False),
    sa.Column('provider_username', sa.String(length=120), nullable=True),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_oauth_accounts_provider_account')
    )
    op.create_index(op.f('ix_oauth_accounts_created_at'), 'oauth_accounts', ['created_at'], unique=False)
    op.create_index('ix_oauth_accounts_user_id', 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('password_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_credentials')),
    sa.UniqueConstraint('user_id', name='uq_password_credentials_user_id')
    )
    op.create_index(op.f('ix_password_credentials_created_at'), 'password_credentials', ['created_at'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='announcement_priority', native_enum=False, length=40), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_announcements_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_announcements_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_index('ix_announcements_cohort_id_published_at', 'announcements', ['cohort_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_announcements_created_at'), 'announcements', ['created_at'], unique=False)
    op.create_index('ix_announcements_is_pinned', 'announcements', ['is_pinned'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('user.registered', 'user.logged_in', 'user.logged_out', 'user.login_failed', 'user.role_changed', 'cohort.created', 'cohort.joined', 'cohort.left', 'cohort.member_role_changed', 'cohort.invite_generated', 'cohort.invite_revoked', 'user.email_verification_sent', 'user.email_verified', 'user.password_reset_requested', 'user.password_reset_completed', 'oauth.account_linked', 'profile.updated', 'channel.created', 'channel.renamed', 'channel.archived', 'channel.restored', 'channel.joined', 'channel.left', 'channel.member_invited', 'channel.member_removed', 'channel.invite_generated', 'channel.invite_revoked', 'message.created', 'message.edited', 'message.deleted', 'message.pinned', 'message.unpinned', 'help_request.created', 'help_request.claimed', 'help_request.unclaimed', 'help_request.resolved', 'help_request.cancelled', 'help_request.reopened', 'decision.created', 'decision.superseded', 'decision.reversed', 'task.created', 'task.assigned', 'task.status_changed', 'announcement.created', 'announcement.updated', 'announcement.deleted', name='audit_action', native_enum=False, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_audit_events_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action_created_at', 'audit_events', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_events_actor_id_created_at', 'audit_events', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('invite_code', sa.String(length=64), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_id'], ['users.id'], name=op.f('fk_channels_archived_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_channels_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_channels_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('cohort_id', 'slug', name='uq_channels_cohort_slug'),
    sa.UniqueConstraint('invite_code', name='uq_channels_invite_code')
    )
    op.create_index('ix_channels_cohort_id_is_archived', 'channels', ['cohort_id', 'is_archived'], unique=False)
    op.create_index(op.f('ix_channels_created_at'), 'channels', ['created_at'], unique=False)
    op.create_table('cohort_memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='cohort_role', native_enum=False, length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('current_project', sa.String(length=160), nullable=True),
    sa.Column('project_area', sa.String(length=80), nullable=True),
    sa.Column('working_status', sa.Enum('available_to_help', 'building', 'in_focus_mode', 'blocked', 'away', name='working_status', native_enum=False, length=40), nullable=False),
    sa.Column('available_to_help', sa.Boolean(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_cohort_memberships_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cohort_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohort_memberships')),
    sa.UniqueConstraint('cohort_id', 'user_id', name='uq_cohort_memberships_cohort_user')
    )
    op.create_index('ix_cohort_memberships_available_to_help', 'cohort_memberships', ['cohort_id', 'available_to_help'], unique=False)
    op.create_index('ix_cohort_memberships_cohort_id_role', 'cohort_memberships', ['cohort_id', 'role'], unique=False)
    op.create_index(op.f('ix_cohort_memberships_created_at'), 'cohort_memberships', ['created_at'], unique=False)
    op.create_index('ix_cohort_memberships_user_id', 'cohort_memberships', ['user_id'], unique=False)
    op.create_table('direct_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('pair_key', sa.String(length=80), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_direct_conversations_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_direct_conversations_created_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direct_conversations')),
    sa.UniqueConstraint('cohort_id', 'pair_key', name='uq_direct_conversations_cohort_pair')
    )
    op.create_index(op.f('ix_direct_conversations_created_at'), 'direct_conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_direct_conversations_last_message_at'), 'direct_conversations', ['last_message_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active_cohort_id', sa.Uuid(), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['active_cohort_id'], ['cohorts.id'], name=op.f('fk_sessions_active_cohort_id_cohorts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name='uq_sessions_token_hash')
    )
    op.create_index('ix_sessions_user_id_expires_at', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('channel_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_channel_members_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_members')),
    sa.UniqueConstraint('channel_id', 'user_id', name='uq_channel_members_channel_user')
    )
    op.create_index('ix_channel_members_user_id', 'channel_members', ['user_id'], unique=False)
    op.create_table('direct_conversation_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['direct_conversations.id'], name=op.f('fk_direct_conversation_members_conversation_id_direct_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_direct_conversation_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direct_conversation_members')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_direct_conversation_members_conversation_user')
    )
    op.create_index('ix_direct_conversation_members_user_id', 'direct_conversation_members', ['user_id'], unique=False)
    op.create_table('membership_skills',
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_membership_skills_position_non_negative')),
    sa.ForeignKeyConstraint(['membership_id'], ['cohort_memberships.id'], name=op.f('fk_membership_skills_membership_id_cohort_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_membership_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'skill_id', name=op.f('pk_membership_skills'))
    )
    op.create_index('ix_membership_skills_skill_id', 'membership_skills', ['skill_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), server_default=sa.text("nextval('message_seq')"), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('direct_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('parent_message_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('text', 'system', 'announcement', name='message_type', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned_by_id', sa.Uuid(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(body, ''))", persisted=True), nullable=True),
    sa.CheckConstraint('(channel_id IS NOT NULL AND direct_conversation_id IS NULL) OR (channel_id IS NULL AND direct_conversation_id IS NOT NULL)', name=op.f('ck_messages_exactly_one_destination')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_messages_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_messages_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_messages_deleted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['direct_conversation_id'], ['direct_conversations.id'], name=op.f('fk_messages_direct_conversation_id_direct_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_messages_parent_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by_id'], ['users.id'], name=op.f('fk_messages_pinned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_channel_id_created_at', 'messages', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_messages_channel_id_id', 'messages', ['channel_id', 'id'], unique=False)
    op.create_index('ix_messages_cohort_id_created_at', 'messages', ['cohort_id', 'created_at'], unique=False)
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['direct_conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_is_pinned', 'messages', ['is_pinned'], unique=False)
    op.create_index('ix_messages_parent_message_id', 'messages', ['parent_message_id'], unique=False)
    op.create_index('ix_messages_search_vector', 'messages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_messages_sender_id_created_at', 'messages', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_seq'), 'messages', ['seq'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('original_message_id', sa.Uuid(), nullable=True),
    sa.Column('source_channel_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('related_project', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('active', 'superseded', 'reversed', name='decision_status', native_enum=False, length=40), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(decision_text, '') || ' ' || coalesce(context, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'reversed') OR (reversed_at IS NOT NULL)", name=op.f('ck_decisions_reversed_requires_timestamp')),
    sa.CheckConstraint("(status = 'superseded' AND superseded_by_id IS NOT NULL) OR (status <> 'superseded' AND superseded_by_id IS NULL)", name=op.f('ck_decisions_superseded_requires_replacement')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_decisions_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_decisions_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_message_id'], ['messages.id'], name=op.f('fk_decisions_original_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_id'], ['users.id'], name=op.f('fk_decisions_reversed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['channels.id'], name=op.f('fk_decisions_source_channel_id_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decisions.id'], name=op.f('fk_decisions_superseded_by_id_decisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_author_id', 'decisions', ['author_id'], unique=False)
    op.create_index('ix_decisions_cohort_id_status', 'decisions', ['cohort_id', 'status'], unique=False)
    op.create_index(op.f('ix_decisions_created_at'), 'decisions', ['created_at'], unique=False)
    op.create_index('ix_decisions_search_vector', 'decisions', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_decisions_source_channel_id', 'decisions', ['source_channel_id'], unique=False)
    op.create_table('help_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_message_id', sa.Uuid(), nullable=True),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('source_channel_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('coding', 'design', 'deployment', 'research', 'product', 'feedback', 'other', name='help_category', native_enum=False, length=40), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'normal', 'high', 'urgent', name='help_urgency', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'resolved', 'cancelled', name='help_request_status', native_enum=False, length=40), nullable=False),
    sa.Column('assigned_helper_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'claimed') OR (assigned_helper_id IS NOT NULL AND claimed_at IS NOT NULL)", name=op.f('ck_help_requests_claimed_requires_helper')),
    sa.CheckConstraint("(status <> 'open') OR (assigned_helper_id IS NULL)", name=op.f('ck_help_requests_open_has_no_helper')),
    sa.CheckConstraint("(status <> 'resolved') OR (resolved_at IS NOT NULL)", name=op.f('ck_help_requests_resolved_requires_timestamp')),
    sa.ForeignKeyConstraint(['assigned_helper_id'], ['users.id'], name=op.f('fk_help_requests_assigned_helper_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_help_requests_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_message_id'], ['messages.id'], name=op.f('fk_help_requests_original_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_help_requests_requester_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['channels.id'], name=op.f('fk_help_requests_source_channel_id_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_requests'))
    )
    op.create_index('ix_help_requests_assigned_helper_id', 'help_requests', ['assigned_helper_id'], unique=False)
    op.create_index('ix_help_requests_cohort_id_status', 'help_requests', ['cohort_id', 'status'], unique=False)
    op.create_index(op.f('ix_help_requests_created_at'), 'help_requests', ['created_at'], unique=False)
    op.create_index('ix_help_requests_requester_id', 'help_requests', ['requester_id'], unique=False)
    op.create_index('ix_help_requests_status_created_at', 'help_requests', ['status', 'created_at'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('mention_type', sa.Enum('user', 'channel', 'admins', name='mention_type', native_enum=False, length=40), nullable=False),
    sa.Column('mentioned_user_id', sa.Uuid(), nullable=True),
    sa.Column('raw_text', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(mention_type = 'user' AND mentioned_user_id IS NOT NULL) OR (mention_type <> 'user')", name=op.f('ck_mentions_user_mention_requires_user')),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], name=op.f('fk_mentions_mentioned_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_mentions_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentions'))
    )
    op.create_index('ix_mentions_mentioned_user_id', 'mentions', ['mentioned_user_id'], unique=False)
    op.create_index('ix_mentions_message_id', 'mentions', ['message_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reaction_type', sa.Enum('thumbs_up', 'eyes', 'check', 'celebration', 'heart', name='reaction_type', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_reactions_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reactions')),
    sa.UniqueConstraint('message_id', 'user_id', 'reaction_type', name='uq_reactions_message_user_type')
    )
    op.create_index('ix_reactions_message_id', 'reactions', ['message_id'], unique=False)
    op.create_table('read_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('direct_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('last_read_message_id', sa.Uuid(), nullable=True),
    sa.Column('last_read_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(channel_id IS NOT NULL AND direct_conversation_id IS NULL) OR (channel_id IS NULL AND direct_conversation_id IS NOT NULL)', name=op.f('ck_read_receipts_exactly_one_scope')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_read_receipts_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direct_conversation_id'], ['direct_conversations.id'], name=op.f('fk_read_receipts_direct_conversation_id_direct_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name=op.f('fk_read_receipts_last_read_message_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_read_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_receipts')),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_read_receipts_user_channel'),
    sa.UniqueConstraint('user_id', 'direct_conversation_id', name='uq_read_receipts_user_conversation')
    )
    op.create_index('ix_read_receipts_user_id', 'read_receipts', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('source_channel_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', name='task_status', native_enum=False, length=40), nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority', native_enum=False, length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'done') OR (completed_at IS NOT NULL)", name=op.f('ck_tasks_done_requires_completed_at')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_tasks_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_tasks_creator_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['channels.id'], name=op.f('fk_tasks_source_channel_id_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('fk_tasks_source_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_assignee_id', 'tasks', ['assignee_id'], unique=False)
    op.create_index('ix_tasks_assignee_id_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('ix_tasks_cohort_id_status', 'tasks', ['cohort_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_creator_id', 'tasks', ['creator_id'], unique=False)
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.Enum('mention', 'direct_message', 'thread_reply', 'task_assigned', 'task_status_changed', 'help_request_claimed', 'help_request_assigned', 'help_request_resolved', 'help_request_reopened', 'announcement', 'decision_changed', 'channel_invite', name='notification_type', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link_path', sa.String(length=300), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('direct_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('help_request_id', sa.Uuid(), nullable=True),
    sa.Column('decision_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('announcement_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('fk_notifications_announcement_id_announcements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_notifications_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], name=op.f('fk_notifications_cohort_id_cohorts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_notifications_decision_id_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['direct_conversation_id'], ['direct_conversations.id'], name=op.f('fk_notifications_direct_conversation_id_direct_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['help_request_id'], ['help_requests.id'], name=op.f('fk_notifications_help_request_id_help_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_notifications_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_notifications_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_cohort_recipient_read', 'notifications', ['cohort_id', 'recipient_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_recipient_id_created_at', 'notifications', ['recipient_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_recipient_id_created_at', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('ix_notifications_cohort_recipient_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_index('ix_tasks_creator_id', table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index('ix_tasks_cohort_id_status', table_name='tasks')
    op.drop_index('ix_tasks_assignee_id_status', table_name='tasks')
    op.drop_index('ix_tasks_assignee_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_read_receipts_user_id', table_name='read_receipts')
    op.drop_table('read_receipts')
    op.drop_index('ix_reactions_message_id', table_name='reactions')
    op.drop_table('reactions')
    op.drop_index('ix_mentions_message_id', table_name='mentions')
    op.drop_index('ix_mentions_mentioned_user_id', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('ix_help_requests_status_created_at', table_name='help_requests')
    op.drop_index('ix_help_requests_requester_id', table_name='help_requests')
    op.drop_index(op.f('ix_help_requests_created_at'), table_name='help_requests')
    op.drop_index('ix_help_requests_cohort_id_status', table_name='help_requests')
    op.drop_index('ix_help_requests_assigned_helper_id', table_name='help_requests')
    op.drop_table('help_requests')
    op.drop_index('ix_decisions_source_channel_id', table_name='decisions')
    op.drop_index('ix_decisions_search_vector', table_name='decisions', postgresql_using='gin')
    op.drop_index(op.f('ix_decisions_created_at'), table_name='decisions')
    op.drop_index('ix_decisions_cohort_id_status', table_name='decisions')
    op.drop_index('ix_decisions_author_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_messages_seq'), table_name='messages')
    op.drop_index('ix_messages_sender_id_created_at', table_name='messages')
    op.drop_index('ix_messages_search_vector', table_name='messages', postgresql_using='gin')
    op.drop_index('ix_messages_parent_message_id', table_name='messages')
    op.drop_index('ix_messages_is_pinned', table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_index('ix_messages_cohort_id_created_at', table_name='messages')
    op.drop_index('ix_messages_channel_id_id', table_name='messages')
    op.drop_index('ix_messages_channel_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.execute(sa.schema.DropSequence(sa.Sequence('message_seq')))
    op.drop_index('ix_membership_skills_skill_id', table_name='membership_skills')
    op.drop_table('membership_skills')
    op.drop_index('ix_direct_conversation_members_user_id', table_name='direct_conversation_members')
    op.drop_table('direct_conversation_members')
    op.drop_index('ix_channel_members_user_id', table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index('ix_sessions_user_id_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_direct_conversations_last_message_at'), table_name='direct_conversations')
    op.drop_index(op.f('ix_direct_conversations_created_at'), table_name='direct_conversations')
    op.drop_table('direct_conversations')
    op.drop_index('ix_cohort_memberships_user_id', table_name='cohort_memberships')
    op.drop_index(op.f('ix_cohort_memberships_created_at'), table_name='cohort_memberships')
    op.drop_index('ix_cohort_memberships_cohort_id_role', table_name='cohort_memberships')
    op.drop_index('ix_cohort_memberships_available_to_help', table_name='cohort_memberships')
    op.drop_table('cohort_memberships')
    op.drop_index(op.f('ix_channels_created_at'), table_name='channels')
    op.drop_index('ix_channels_cohort_id_is_archived', table_name='channels')
    op.drop_table('channels')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index('ix_audit_events_actor_id_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_action_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_announcements_is_pinned', table_name='announcements')
    op.drop_index(op.f('ix_announcements_created_at'), table_name='announcements')
    op.drop_index('ix_announcements_cohort_id_published_at', table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_password_credentials_created_at'), table_name='password_credentials')
    op.drop_table('password_credentials')
    op.drop_index('ix_oauth_accounts_user_id', table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_created_at'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('ix_email_tokens_user_id_purpose', table_name='email_tokens')
    op.drop_index('ix_email_tokens_expires_at', table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_cohorts_created_at'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('oauth_states')
    op.drop_index('ix_login_attempts_ip_created_at', table_name='login_attempts')
    op.drop_index('ix_login_attempts_identifier_created_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
